GET http://localhost:8080/person HTTP/1.1

###

GET http://localhost:8080/person/Srow77 HTTP/1.1

###

GET  http://localhost:8080/about HTTP/1.1

###

GET http://localhost:8080/about/6349eb442881d62912e69db3 HTTP/1.1

###

POST http://localhost:8080/person HTTP/1.1
Content-Type: application/json

{
    "username": "Srow77",
    "password": "S#42*Ed",
    "firstName": "Stewart",
    "lastName": "Rowley",
    "email": "stewy.rowley@gmail.com",
    "phoneNumber": "509-301-0726",
    "profile": {
        "degree": "Software Engineering",
        "career": "Web Developer",
        "location": "Walla Walla, Wa"
    }
}

###

POST http://localhost:8080/about HTTP/1.1
Content-Type: application/json

{  
     "_id": "6349eb442881d62912e69db3",
    "skills": ["Tennis", "Programming", "Basketball"],
    "hobbies": ["Board Games", "Watching NHL Hockey", "Sports"]
}

###

GET https://cse341-secured.onrender.com/person HTTP/1.1

###

GET https://cse341-secured.onrender.com/person/Erow44 HTTP/1.1

###

GET  https://cse341-secured.onrender.com/about HTTP/1.1

###

GET https://cse341-secured.onrender.com/about/6349eba1d458bc4bf5ac8f3 HTTP/1.1

###

POST https://cse341-secured.onrender.com/person HTTP/1.1
Content-Type: application/json

{
    "username": "Erow44",
    "password": "E#42*Rd",
    "firstName": "Emily",
    "lastName": "Rowley",
    "email": "emily.rowley@gmail.com",
    "phoneNumber": "509-402-0726",
    "profile": {
        "degree": "Teacher Education",
        "career": "Elementry Teacher",
        "location": "Walla Walla, Wa"
    }
}

###

POST https://cse341-secured.onrender.com/about HTTP/1.1
Content-Type: application/json

{  
     "_id": "6349eba1d458bc4bf5ac8f34",
    "skills": ["Drawing", "Painting", "Design"],
    "hobbies": ["Board Games", "Movies", "Sports"]
}